version: 1.0.{build}
image: Ubuntu2004
build_script:
  - pwsh: |
      dotnet restore JsTimers.sln
      dotnet build JsTimers.sln -c Release
build:
  project: JsTimers.sln
  verbosity: normal
