# version: 1.0.{build}-{branch} # TODO: Update and cleanup this
# image: Visual Studio 2019
# skip_tags: true
# skip_commits:
#   message: /!skip-ci/
# install:
#   - cmd: msbuild -t:restore JsTimers.sln
# build:
#   project: JsTimers.sln
#   verbosity: minimal
#   publish_nuget: true
# configuration:
#   - Release
# artifacts:
#   - path: JsTimers\bin\Release\netstandard2.0\JsTimers.dll
# deploy:
#   - provider: GitHub
#     tag: JsTimers v$(appveyor_build_version)
#     auth_token:
#       secure: 6NC5njRDgZxwvNmpiVm0gPw9yFw4ff7hLFFMA53FTFFB0WtRiWSW+ekc+1A6IABr
#     artifact: /.*\.(nupkg|dll)/
#     prerelease: true
#     on:
#       branch: develop
#   - provider: GitHub
#     tag: JsTimers v1.0.$(appveyor_build_number)
#     auth_token:
#       secure: 6NC5njRDgZxwvNmpiVm0gPw9yFw4ff7hLFFMA53FTFFB0WtRiWSW+ekc+1A6IABr
#     artifact: /.*\.(nupkg|dll)/
#     on:
#       branch: master
version: 1.0.{build}-{branch}
image: Visual Studio 2022
for:
  - only_commits:
      files:
        - '*'
    environment:
      github_access_token:
        secure: oXcOV5MJg+RewNkM3MSV5ZU+gIUZOo8D/4cyW/p5I2ZXD+P2TgTK5ZZfCdQXDG3L
    install:
      - pwsh: git config --global user.name 2chevskii
      - pwsh: git config --global user.email prsroman3@gmail.com
      - pwsh: git config --global credential.helper store
      - pwsh: Set-Content -Path "$HOME/.git-credentials" -Value "https://$($env:github_access_token):x-oauth-basic@github.com`n" -NoNewline
    build_script:
      - pwsh: npm install
      - pwsh: npm run docs:build
      - pwsh: cd docs/.vitepress/dist
      - pwsh: git init
      - pwsh: git add -A
      - pwsh: git commit -m 'Deploy docs#$($env:APPVEYOR_BUILD_NUMBER)'
      - pwsh: git push -f git@github.com:2chevskii/jstimers.git docs:gh-pages
