version: 1.0.{build}-{branch} # TODO: Update and cleanup this
image: Visual Studio 2019
skip_tags: true
skip_commits:
  message: /!skip-ci/
install:
  - cmd: msbuild -t:restore JsTimers.sln
build:
  project: JsTimers.sln
  verbosity: minimal
  publish_nuget: true
configuration:
  - Release
artifacts:
  - path: JsTimers\bin\Release\netstandard2.0\JsTimers.dll
deploy:
  - provider: GitHub
    tag: JsTimers v$(appveyor_build_version)
    auth_token:
      secure: 6NC5njRDgZxwvNmpiVm0gPw9yFw4ff7hLFFMA53FTFFB0WtRiWSW+ekc+1A6IABr
    artifact: /.*\.(nupkg|dll)/
    prerelease: true
    on:
      branch: develop
  - provider: GitHub
    tag: JsTimers v1.0.$(appveyor_build_number)
    auth_token:
      secure: 6NC5njRDgZxwvNmpiVm0gPw9yFw4ff7hLFFMA53FTFFB0WtRiWSW+ekc+1A6IABr
    artifact: /.*\.(nupkg|dll)/
    on:
      branch: master
