version: 1.0.{build}-{branch}
image: Visual Studio 2019
skip_commits:
  files:
    - '**/*.yml'
    - '**/*.editorconfig'
    - '**/*.gitignore'
    - '**/LICENSE'
    - '**/*.md'
install:
  - cmd: msbuild -t:restore JsTimers.sln
build:
  project: JsTimers.sln
  verbosity: minimal
after_build:
  - cmd: msbuild -t:pack JsTimers.sln -property:Configuration=Release
configuration:
  - Debug
  - Release
