version: 1.0.{build}-{branch}
image: Visual Studio 2019
install:
  - cmd: IF %CONFIGURATION%==Release (msbuild -t:restore JsTimers/JsTimers.csproj) ELSE (msbuild -t:restore JsTimers.sln)
build:
  project: JsTimers.sln
  verbosity: minimal
after_build:
  - cmd: IF %CONFIGURATION%==Release (msbuild -t:pack -property:Configuration=Release JsTimers.sln)
configuration:
  - Debug
  - Release
artifacts:
  - path: bin/Packages/JsTimers.1.0.*.nupkg
    name: JsTimers.1.0.$(APPVEYOR_BUILD_NUMBER)
