version: 1.0.{build}-{branch}
image: Visual Studio 2019
install:
  - cmd: msbuild -t:restore JsTimers.sln
build:
  project: JsTimers.sln
  verbosity: minimal
after_build:
  - cmd: msbuild -t:pack JsTimers.sln -property:Configuration=Release
configuration:
  - Debug
  - Release
artifacts:
  - path: bin/Release/JsTimers.{version}.nupkg
