# version: 1.0.{build}-{branch} # TODO: Update and cleanup this
# image: Visual Studio 2019
# skip_tags: true
# skip_commits:
#   message: /!skip-ci/
# install:
#   - cmd: msbuild -t:restore JsTimers.sln
# build:
#   project: JsTimers.sln
#   verbosity: minimal
#   publish_nuget: true
# configuration:
#   - Release
# artifacts:
#   - path: JsTimers\bin\Release\netstandard2.0\JsTimers.dll
# deploy:
#   - provider: GitHub
#     tag: JsTimers v$(appveyor_build_version)
#     auth_token:
#       secure: 6NC5njRDgZxwvNmpiVm0gPw9yFw4ff7hLFFMA53FTFFB0WtRiWSW+ekc+1A6IABr
#     artifact: /.*\.(nupkg|dll)/
#     prerelease: true
#     on:
#       branch: develop
#   - provider: GitHub
#     tag: JsTimers v1.0.$(appveyor_build_number)
#     auth_token:
#       secure: 6NC5njRDgZxwvNmpiVm0gPw9yFw4ff7hLFFMA53FTFFB0WtRiWSW+ekc+1A6IABr
#     artifact: /.*\.(nupkg|dll)/
#     on:
#       branch: master
version: '{build}'
image: Visual Studio 2022
environment:
  GITHUB_ACCESS_TOKEN:
    secure: ClKZOQeKEaL9+34YfQ7cdU4shau8SPy90UvKfaI/HhnepikI6P4BeMyX/GYfpnLs
  NUGET_API_KEY:
    secure: 5llcjQ7ZU0MacQj4HoqZdfXFgeY1HV5uUDkjpkOBXI3eYD/ZNfHvDSFBJV1FHbn1
for:
  - only_commits:
      files:
        - 'docs/**/*'
    branches:
      only:
        - master
    install:
      - ps: git config --global user.name 2chevskii
      - ps: git config --global user.email prsroman3@gmail.com
      - pwsh: npm install --no-package-lock # fuck fuck fuck fuck fuck
    build_script:
      - pwsh: npm run docs:build
      - ps: cd docs/.vitepress/dist
      - ps: git init --initial-branch=master
      - ps: git add -A
      - ps: 'git commit -m "Documentation deploy #$($env:APPVEYOR_BUILD_NUMBER)"'
      - pwsh: 'git push -f "https://2chevskii:$($env:GITHUB_ACCESS_TOKEN)@github.com/2chevskii/JsTimers.git" master:gh-pages'
    test: false
  - only_commits:
      files:
        - 'JsTimers/**/*'
        - 'JsTimers.Test/**/*'
        - 'JsTimers.Tests/**/*'
        - 'appveyor.yml'
        - 'Directory.Build.props'
        - 'JsTimers.sln'
    install:
      - ps: msbuild -t:restore JsTimers.sln
    build:
      project: JsTimers.sln
      publish_nuget: true
      publish_nuget_symbols: true
    configuration:
      - Release
    test:
      assemblies:
        only:
          - JsTimers.Tests/bin/Release/netcoreapp3.1/JsTimers.Tests.dll
    deploy:
      - provider: GitHub # Create GitHub release, if tag is pure semver core (0.0.0)
        name: GitHub Release
        on:
          branch: /\d+\.\d+\.\d+/
        tag: $(appveyor_repo_tag_name)
        auth_token: $(GITHUB_ACCESS_TOKEN)
        prerelease: false
        artifact: /.*\.(nupkg|dll)/
      - provider: GitHub # Create GitHub pre-release, if tag contains suffix (0.0.0-alpha)
        name: GitHub PreRelease
        on:
          branch: /\d+\.\d+\.\d+-.+/
        tag: $(appveyor_repo_tag_name)
        auth_token: $(GITHUB_ACCESS_TOKEN)
        prerelease: true
        artifact: /.*\.(nupkg|dll)/
      - provider: NuGet # Push to nuget.org package registry
        on:
          branch: /\d+\.\d+\.\d+(?:-.+)?/
        artifact: /.*\.(s?nupkg)/
        skip_symbols: false
        api_key: $(NUGET_API_KEY)
      - provider: NuGet # Push to GitHub NuGet package registry
        server: https://nuget.pkg.github.com/2chevskii/index.json
        artifact: /.*\.(s?nupkg)/
        username: 2chevskii
        api_key: $(GITHUB_ACCESS_TOKEN)
        on:
          branch: /\d+\.\d+\.\d+(?:-.+)?/
        # skip_symbols: true
