version: 1.0.{build}-{branch}
image: Visual Studio 2019
install:
  - cmd: msbuild -t:restore JsTimers.sln
build:
  project: JsTimers.sln
  verbosity: minimal
  publish_nuget: true
configuration:
  - Release
artifacts:
  - path: JsTimers\bin\Release\netstandard2.0\JsTimers.dll
